ALTER TABLE ship_compliance
  ADD COLUMN IF NOT EXISTS target_intensity NUMERIC(10,4) NOT NULL DEFAULT 89.3368,
  ADD COLUMN IF NOT EXISTS actual_intensity  NUMERIC(10,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS energy_in_scope   NUMERIC(18,2) NOT NULL DEFAULT 0;